### ISSUE TITLE
Mango xperia mini pro Wifi not getting enabled

### ISSUE THREAD

**Issue by thak123** [LegacyXperia/local_manifests#119]
I tried putting on the Wifi after the install but doesnt seem to turn on wifi.
Neither from shortcut not from the settings ->Wifi option

**Comment by ghost** [comment]
Calibration seems to be broken.
Works fine once you do it manually.

http://forum.xda-developers.com/showpost.php?p=47008262&postcount=68

**Comment by thak123** [comment]
Thanks for the swift reply works fine .....:)

**Comment by mikeNG** [comment]
Fixed in latest build

**Comment by thak123** [comment]
I tried the above link it worked but now i upadted with latest release and wifi still not working ,Any solution

**Comment by ghost** [comment]
Did you remember to flash the new kernel?

**Comment by thak123** [comment]
Oh no !!! where is the new kernel

On Thu, Nov 21, 2013 at 11:43 PM, stashcroft notifications@github.comwrote:

> Did you remember to flash the new kernel?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LegacyXperia/local_manifests/issues/119#issuecomment-29008612
> .

## 
-  Regards:*
  Gaurish P Thakkar

**Comment by ghost** [comment]
You need to extract the boot.img from the build and install it with fastboot or Flashtool.

**Comment by thak123** [comment]
Yes i got it thanks .

On Sat, Nov 23, 2013 at 11:34 PM, stashcroft notifications@github.comwrote:

> You need to extract the boot.img from the build and install it with
> fastboot or Flashtool.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LegacyXperia/local_manifests/issues/119#issuecomment-29137724
> .

## 
-  Regards:*
  Gaurish P Thakkar
