### ISSUE TITLE
[CM11.0-20131127-coconut] Music Conflict with Screen Lock Sounds (not the Notification Sounds)

### ISSUE THREAD

**Issue by azakosath** [LegacyXperia/local_manifests#180]
Hi Mike,
while listening to music (using Apollo) and trying to unlock or lock the screen, there is a sound distortion. The issue doesn't happen if notification sounds are muted. Please, let me know if you need any kind of logs for this issue.

**Comment by JovieBrett** [comment]
Confirmed on Smultron :-) Anyway volume sound is improved! Much louder than before :D

**Comment by azakosath** [comment]
I noticed that when I received a message from Hangouts while I was listening to music, there was no conflict in the sound. So, the only conflict exists between music and Screen lock sounds, because if you unckeck this ckeckbox in sound settings there is no sound distortion when you lock or unlock the screen. I captured two different logcats for this issue, there they are:
https://gist.github.com/azakosath/7718175

I know this is a bug we can live with, but I hope it will get fixed....;-)

**Comment by cajhin** [comment]
Seems to be a common problem.
When Settings > Sound > Screen lock sound is enabled,
music stutters badly when the screen is turned off, or unlocked.

kmsg does not show anything.
logcat is quite consistent (same results every time).
The only difference between "stutter" and "no stutter" that stands out is that "no stutter" there is some I/Choreographer skipping frames

---

bad turn off (stutters):

12:44:24.516 I/PowerManagerService(  605): Going to sleep by user request...
12:44:25.135 W/keystore(  243): permission denied for 10003: zero
12:44:25.212 I/audio_a2dp_hw(  240): out_set_parameters: state 1
12:44:25.212 I/str_params(  240): key: 'routing' value: '128'
12:44:25.228 I/wpa_supplicant( 5228): wpa_driver_nl80211_driver_cmd: Unsupported command SETSUSPENDMODE 1
12:44:25.259 I/audio_a2dp_hw(  240): adev_set_parameters: state 1
12:44:25.259 I/audio_a2dp_hw(  240): out_set_parameters: state 1
12:44:25.274 I/str_params(  240): key: 'screen_state' value: 'off'
12:44:25.290 W/keystore(  243): permission denied for 10003: zero
12:44:25.290 D/LightsService(  605): Excessive delay setting light: 159ms
12:44:25.290 D/SurfaceFlinger(  235): Screen released, type=0 flinger=0xed8450
12:44:25.398 W/keystore(  243): permission denied for 10003: zero
12:44:25.429 W/keystore(  243): permission denied for 10003: zero
12:44:25.429 W/keystore(  243): permission denied for 10003: zero
12:44:25.444 W/keystore(  243): permission denied for 10003: zero
12:44:25.506 V/Avrcp   ( 5410): received RCC_CHANGED_ACTION
12:44:25.506 V/Avrcp   ( 5410): focus: false , availability: true
12:44:25.506 V/Avrcp   ( 5410): MSG_UPDATE_RCC_CHANGE
12:44:25.506 V/Avrcp   ( 5410): processRCCStateChange
12:44:25.506 V/Avrcp   ( 5410): isResetFocusRequired: false
12:44:25.506 V/MediaFocusControl(  605): updating focussed RCC change to RCD: CallingPackageName:com.andrew.apollo isFocussed:false isAvailable:true
12:44:25.506 V/Avrcp   ( 5410): received RCC_CHANGED_ACTION
12:44:25.506 V/Avrcp   ( 5410): focus: true , availability: true
12:44:25.506 V/Avrcp   ( 5410): MSG_UPDATE_RCC_CHANGE
12:44:25.506 V/Avrcp   ( 5410): processRCCStateChange
12:44:25.506 V/Avrcp   ( 5410): isResetFocusRequired: true
12:44:25.506 V/Avrcp   ( 5410): setting com.andrew.apollo focus: false
12:44:25.506 V/Avrcp   ( 5410): setting com.andrew.apollo focus: false
12:44:25.522 V/MediaFocusControl(  605): updating focussed RCC change to RCD: CallingPackageName:com.andrew.apollo isFocussed:true isAvailable:true
12:44:25.522 D/SurfaceControl(  605): Excessive delay in blankDisplay() while turning screen off: 234ms
12:44:25.537 W/keystore(  243): permission denied for 10003: zero
12:44:25.552 W/keystore(  243): permission denied for 10003: zero
12:44:25.583 W/keystore(  243): permission denied for 10003: zero
12:44:25.599 W/keystore(  243): permission denied for 10003: zero
12:44:25.614 W/keystore(  243): permission denied for 10003: zero
12:44:25.676 W/TransportControlView(  707): Updating seek bars; received invalid estimated media position (-1). Disabling seek.
12:44:25.738 D/PhoneStatusBar(  707): disable: < expand icons alerts ticker system_info BACK\* HOME\* RECENT\* clock SEARCH\* >

---

good turn off (no stutter):

12:55:01.611 I/PowerManagerService(  605): Going to sleep by user request...
12:55:02.158 W/keystore(  243): permission denied for 10003: zero
12:55:02.267 I/wpa_supplicant( 5228): wpa_driver_nl80211_driver_cmd: Unsupported command SETSUSPENDMODE 1
12:55:02.283 I/audio_a2dp_hw(  240): adev_set_parameters: state 1
12:55:02.283 I/audio_a2dp_hw(  240): out_set_parameters: state 1
12:55:02.283 I/str_params(  240): key: 'screen_state' value: 'off'
12:55:02.299 W/keystore(  243): permission denied for 10003: zero
12:55:02.408 D/LightsService(  605): Excessive delay setting light: 278ms
12:55:02.486 D/SurfaceFlinger(  235): Screen released, type=0 flinger=0xed8450
12:55:02.720 W/keystore(  243): permission denied for 10003: zero
12:55:02.752 D/SurfaceControl(  605): Excessive delay in blankDisplay() while turning screen off: 271ms
12:55:02.767 W/keystore(  243): permission denied for 10003: zero
12:55:02.799 W/keystore(  243): permission denied for 10003: zero
12:55:02.814 W/keystore(  243): permission denied for 10003: zero
12:55:02.877 V/Avrcp   ( 5410): received RCC_CHANGED_ACTION
12:55:02.892 V/Avrcp   ( 5410): focus: false , availability: true
12:55:02.892 V/Avrcp   ( 5410): MSG_UPDATE_RCC_CHANGE
12:55:02.892 V/Avrcp   ( 5410): processRCCStateChange
12:55:02.892 V/Avrcp   ( 5410): isResetFocusRequired: false
12:55:02.892 V/MediaFocusControl(  605): updating focussed RCC change to RCD: CallingPackageName:com.andrew.apollo isFocussed:false isAvailable:true
12:55:02.892 V/Avrcp   ( 5410): received RCC_CHANGED_ACTION
12:55:02.892 V/Avrcp   ( 5410): focus: true , availability: true
12:55:02.892 V/Avrcp   ( 5410): MSG_UPDATE_RCC_CHANGE
12:55:02.892 V/Avrcp   ( 5410): processRCCStateChange
12:55:02.892 V/Avrcp   ( 5410): isResetFocusRequired: true
12:55:02.892 V/Avrcp   ( 5410): setting com.andrew.apollo focus: false
12:55:02.892 V/Avrcp   ( 5410): setting com.andrew.apollo focus: false
12:55:02.892 V/MediaFocusControl(  605): updating focussed RCC change to RCD: CallingPackageName:com.andrew.apollo isFocussed:true isAvailable:true
12:55:02.939 W/keystore(  243): permission denied for 10003: zero
12:55:02.939 W/keystore(  243): permission denied for 10003: zero
12:55:02.955 W/keystore(  243): permission denied for 10003: zero
12:55:03.002 W/keystore(  243): permission denied for 10003: zero
12:55:03.002 W/keystore(  243): permission denied for 10003: zero
12:55:03.002 I/Choreographer(  707): Skipped 48 frames!  The application may be doing too much work on its main thread.
12:55:03.095 D/PowerManagerService-JNI(  605): Excessive delay in autosuspend_enable() while turning screen off: 343ms
12:55:03.173 W/TransportControlView(  707): Updating seek bars; received invalid estimated media position (-1). Disabling seek.
12:55:03.189 D/PhoneStatusBar(  707): disable: < expand icons alerts ticker system_info BACK\* HOME\* RECENT\* clock SEARCH\* >

**Comment by mikeNG** [comment]
Might be fixed in next build, I have a possible fix but I won't be able to test it until Monday

**Comment by mikeNG** [comment]
fixed

**Comment by azakosath** [comment]
Mike, the issue came back... This time the conflict is with notification sound of the app Viber (https://play.google.com/store/apps/details?id=com.viber.voip&hl=en). It should had been there from day one, but I've just noticed it. When I'm using hangouts you have just a slight decrease in music's volume, but with viber the distortion is the same as it was with screen's lock/unlock sound. The logcat doesn't show anything. Should I open a new issue, or are you going to reopen this one?
