### ISSUE TITLE
[cm-11.0-20131210-LX-NIGHTLY-haida] Android.Process.Media FC's 

### ISSUE THREAD

**Issue by mavado83** [LegacyXperia/local_manifests#257]
Not able to enter the Play Store. Closes due to android.process.media FC.

A fix was in the previous cherry picks update.sh,  but the committer said 'Use AOSP fix' possibly this fix is not merged? 

Logcat:

--------- beginning of /dev/log/main
E/Term    ( 3988): onCreate
E/Term    ( 3988): onCreate
E/InputDispatcher(  607): channel '41c94dd0 com.android.vending/com.android.vending.AssetBrowserActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/InputDispatcher(  607): channel '41f0a780 com.android.vending/com.google.android.finsky.activities.TosActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
--------- beginning of /dev/log/system
E/AndroidRuntime( 4406): FATAL EXCEPTION: main
E/AndroidRuntime( 4406): Process: android.process.media, PID: 4406
E/AndroidRuntime( 4406): java.lang.UnsatisfiedLinkError: Native method not found: android.os.FileUtils.getVolumeUUID:(Ljava/lang/String;)I
E/AndroidRuntime( 4406):    at android.os.FileUtils.getVolumeUUID(Native Method)
E/AndroidRuntime( 4406):    at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5269)
E/AndroidRuntime( 4406):    at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:608)
E/AndroidRuntime( 4406):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 4406):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 4406):    at android.app.ActivityThread.installProvider(ActivityThread.java:4854)
E/AndroidRuntime( 4406):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4449)
E/AndroidRuntime( 4406):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4389)
E/AndroidRuntime( 4406):    at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime( 4406):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime( 4406):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4406):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4406):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 4406):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4406):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4406):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 4406):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 4406):    at dalvik.system.NativeStart.main(Native Method)
E/Term    ( 3988): onCreate
E/su      ( 4446): sqlite3 open failure: 14
E/cutils-trace( 4447): Error opening trace file: No such file or directory (2)
E/memtrack( 4447): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 4447): failed to load memtrack module: -2
E/cutils-trace( 4475): Error opening trace file: No such file or directory (2)
E/memtrack( 4475): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 4475): failed to load memtrack module: -2
E/AndroidRuntime( 4527): FATAL EXCEPTION: main
E/AndroidRuntime( 4527): Process: android.process.media, PID: 4527
E/AndroidRuntime( 4527): java.lang.UnsatisfiedLinkError: Native method not found: android.os.FileUtils.getVolumeUUID:(Ljava/lang/String;)I
E/AndroidRuntime( 4527):    at android.os.FileUtils.getVolumeUUID(Native Method)
E/AndroidRuntime( 4527):    at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5269)
E/AndroidRuntime( 4527):    at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:608)
E/AndroidRuntime( 4527):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 4527):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 4527):    at android.app.ActivityThread.installProvider(ActivityThread.java:4854)
E/AndroidRuntime( 4527):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4449)
E/AndroidRuntime( 4527):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4389)
E/AndroidRuntime( 4527):    at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime( 4527):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime( 4527):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4527):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4527):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 4527):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4527):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4527):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 4527):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 4527):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4548): FATAL EXCEPTION: main
E/AndroidRuntime( 4548): Process: android.process.media, PID: 4548
E/AndroidRuntime( 4548): java.lang.UnsatisfiedLinkError: Native method not found: android.os.FileUtils.getVolumeUUID:(Ljava/lang/String;)I
E/AndroidRuntime( 4548):    at android.os.FileUtils.getVolumeUUID(Native Method)
E/AndroidRuntime( 4548):    at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5269)
E/AndroidRuntime( 4548):    at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:608)
E/AndroidRuntime( 4548):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 4548):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 4548):    at android.app.ActivityThread.installProvider(ActivityThread.java:4854)
E/AndroidRuntime( 4548):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4449)
E/AndroidRuntime( 4548):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4389)
E/AndroidRuntime( 4548):    at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime( 4548):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime( 4548):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4548):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4548):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 4548):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4548):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4548):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 4548):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 4548):    at dalvik.system.NativeStart.main(Native Method)
E/ActivityThread( 4496): Failed to find provider info for downloads
E/AndroidRuntime( 4567): FATAL EXCEPTION: main
E/AndroidRuntime( 4567): Process: android.process.media, PID: 4567
E/AndroidRuntime( 4567): java.lang.UnsatisfiedLinkError: Native method not found: android.os.FileUtils.getVolumeUUID:(Ljava/lang/String;)I
E/AndroidRuntime( 4567):    at android.os.FileUtils.getVolumeUUID(Native Method)
E/AndroidRuntime( 4567):    at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5269)
E/AndroidRuntime( 4567):    at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:608)
E/AndroidRuntime( 4567):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 4567):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 4567):    at android.app.ActivityThread.installProvider(ActivityThread.java:4854)
E/AndroidRuntime( 4567):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4449)
E/AndroidRuntime( 4567):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4389)
E/AndroidRuntime( 4567):    at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime( 4567):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime( 4567):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4567):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4567):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 4567):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4567):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4567):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 4567):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 4567):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4582): FATAL EXCEPTION: main
E/AndroidRuntime( 4582): Process: android.process.media, PID: 4582
E/AndroidRuntime( 4582): java.lang.UnsatisfiedLinkError: Native method not found: android.os.FileUtils.getVolumeUUID:(Ljava/lang/String;)I
E/AndroidRuntime( 4582):    at android.os.FileUtils.getVolumeUUID(Native Method)
E/AndroidRuntime( 4582):    at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5269)
E/AndroidRuntime( 4582):    at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:608)
E/AndroidRuntime( 4582):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 4582):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 4582):    at android.app.ActivityThread.installProvider(ActivityThread.java:4854)
E/AndroidRuntime( 4582):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4449)
E/AndroidRuntime( 4582):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4389)
E/AndroidRuntime( 4582):    at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime( 4582):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime( 4582):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4582):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4582):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 4582):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4582):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4582):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 4582):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 4582):    at dalvik.system.NativeStart.main(Native Method)
E/ActivityThread( 4496): Failed to find provider info for downloads
E/InputDispatcher(  607): channel '41f120e0 com.android.vending/com.android.vending.AssetBrowserActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/InputDispatcher(  607): channel '41dac420 com.android.vending/com.google.android.finsky.activities.TosActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/AndroidRuntime( 4627): FATAL EXCEPTION: main
E/AndroidRuntime( 4627): Process: android.process.media, PID: 4627
E/AndroidRuntime( 4627): java.lang.UnsatisfiedLinkError: Native method not found: android.os.FileUtils.getVolumeUUID:(Ljava/lang/String;)I
E/AndroidRuntime( 4627):    at android.os.FileUtils.getVolumeUUID(Native Method)
E/AndroidRuntime( 4627):    at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5269)
E/AndroidRuntime( 4627):    at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:608)
E/AndroidRuntime( 4627):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 4627):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 4627):    at android.app.ActivityThread.installProvider(ActivityThread.java:4854)
E/AndroidRuntime( 4627):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4449)
E/AndroidRuntime( 4627):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4389)
E/AndroidRuntime( 4627):    at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime( 4627):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime( 4627):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4627):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4627):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 4627):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4627):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4627):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 4627):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 4627):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4644): FATAL EXCEPTION: main
E/AndroidRuntime( 4644): Process: android.process.media, PID: 4644
E/AndroidRuntime( 4644): java.lang.UnsatisfiedLinkError: Native method not found: android.os.FileUtils.getVolumeUUID:(Ljava/lang/String;)I
E/AndroidRuntime( 4644):    at android.os.FileUtils.getVolumeUUID(Native Method)
E/AndroidRuntime( 4644):    at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5269)
E/AndroidRuntime( 4644):    at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:608)
E/AndroidRuntime( 4644):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 4644):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 4644):    at android.app.ActivityThread.installProvider(ActivityThread.java:4854)
E/AndroidRuntime( 4644):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4449)
E/AndroidRuntime( 4644):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4389)
E/AndroidRuntime( 4644):    at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime( 4644):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime( 4644):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4644):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4644):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 4644):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4644):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4644):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 4644):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 4644):    at dalvik.system.NativeStart.main(Native Method)
E/ActivityThread( 4596): Failed to find provider info for downloads
E/AndroidRuntime( 4662): FATAL EXCEPTION: main
E/AndroidRuntime( 4662): Process: android.process.media, PID: 4662
E/AndroidRuntime( 4662): java.lang.UnsatisfiedLinkError: Native method not found: android.os.FileUtils.getVolumeUUID:(Ljava/lang/String;)I
E/AndroidRuntime( 4662):    at android.os.FileUtils.getVolumeUUID(Native Method)
E/AndroidRuntime( 4662):    at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5269)
E/AndroidRuntime( 4662):    at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:608)
E/AndroidRuntime( 4662):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 4662):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 4662):    at android.app.ActivityThread.installProvider(ActivityThread.java:4854)
E/AndroidRuntime( 4662):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4449)
E/AndroidRuntime( 4662):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4389)
E/AndroidRuntime( 4662):    at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime( 4662):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime( 4662):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4662):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4662):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 4662):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4662):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4662):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 4662):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 4662):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4680): FATAL EXCEPTION: main
E/AndroidRuntime( 4680): Process: android.process.media, PID: 4680
E/AndroidRuntime( 4680): java.lang.UnsatisfiedLinkError: Native method not found: android.os.FileUtils.getVolumeUUID:(Ljava/lang/String;)I
E/AndroidRuntime( 4680):    at android.os.FileUtils.getVolumeUUID(Native Method)
E/AndroidRuntime( 4680):    at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5269)
E/AndroidRuntime( 4680):    at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:608)
E/AndroidRuntime( 4680):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 4680):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 4680):    at android.app.ActivityThread.installProvider(ActivityThread.java:4854)
E/AndroidRuntime( 4680):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4449)
E/AndroidRuntime( 4680):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4389)
E/AndroidRuntime( 4680):    at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime( 4680):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime( 4680):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4680):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4680):    at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 4680):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4680):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4680):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 4680):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 4680):    at dalvik.system.NativeStart.main(Native Method)
E/Term    ( 3988): onCreate
E/Term    ( 3988): onCreate
E/cutils-trace( 4728): Error opening trace file: No such file or directory (2)
E/memtrack( 4728): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 4728): failed to load memtrack module: -2

**Comment by fakhrodin** [comment]
http://forum.xda-developers.com/showpost.php?p=48334277&postcount=325
This worked for my Anzu
give it a try (after back up of course!)
@mikeNG 
Plz add it to instructions
tnx

**Comment by o2droid** [comment]
Formatting SDCard helps but not in my case. ADB log from the crash below:
E/AndroidRuntime( 1305): FATAL EXCEPTION: main
E/AndroidRuntime( 1305): Process: android.process.media, PID: 1305
E/AndroidRuntime( 1305): java.lang.UnsatisfiedLinkError: Native method not found: android.os.FileUtils.getVolumeUUID:(Lj
ava/lang/String;)I
E/AndroidRuntime( 1305):        at android.os.FileUtils.getVolumeUUID(Native Method)
E/AndroidRuntime( 1305):        at com.android.providers.media.MediaProvider.attachVolume(MediaProvider.java:5269)
E/AndroidRuntime( 1305):        at com.android.providers.media.MediaProvider.onCreate(MediaProvider.java:608)
E/AndroidRuntime( 1305):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 1305):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 1305):        at android.app.ActivityThread.installProvider(ActivityThread.java:4854)
E/AndroidRuntime( 1305):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4449)
E/AndroidRuntime( 1305):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4389)
E/AndroidRuntime( 1305):        at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime( 1305):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime( 1305):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1305):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 1305):        at android.app.ActivityThread.main(ActivityThread.java:5081)
E/AndroidRuntime( 1305):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1305):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1305):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 1305):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 1305):        at dalvik.system.NativeStart.main(Native Method)

**Comment by padishah** [comment]
the same on [cm-11.0-20131210-LX-NIGHTLY-iyokan]. formating sd didnt help although without sd no force closes

**Comment by mavado83** [comment]
This solution works for me:
Flash CM11 zip and gapps as normal.
Boot into CM....you will now get the FC. 

Goto settings - storage - format SD card.
The FC does not happen again.

So you must format the SDcard from within android. That's the clue.

**Comment by mikeNG** [comment]
This is a CM bug, will be probably fixed in next build. If anyone builds from source you can try syncing & building the latest source to test this.

**Comment by xange** [comment]
@mavado83 , format sd doesn't solve my problems. the FC message keep popping up since SD card is insert, unmount SD will make everything works normal (as long as SD is mounted, FC message will pop up went media provider is triggered.

**Comment by mavado83** [comment]
@mikeNG , I build from sources. Will try it today

**Comment by mavado83** [comment]
Built from source with the latest updates, and the exception does not happen so far. (did a clean install, without wiping SD card.) So It seems solved in the latest CM built. 
Bug can be closed

**Comment by o2droid** [comment]
Alpha 3 fixes this problem. Bug can be closed
