### ISSUE TITLE
[CM11]{Smultron} Dalvik cache fills up rapidly!

### ISSUE THREAD

**Issue by JovieBrett** [LegacyXperia/local_manifests#351]
CM11 122513 - Smultron
Dalvik cache fills up the /data quickly even if I never enabled ART in the first place since I flashed latest build.
-I followed all the instructions correctly for the new system partition layout.
-Flashed the right kernel
-Performed clean install
-I'm using Link2SD to link user apps to ext4 partition.
-Tried to manually relink all apps using Link2SD but in the middle of the linking process, the device suddenly soft-reboots itself (logcat attached below)
-For some cases, if  /data partition is full, android.process.media following some apps will force close.
-Some user apps that is linked via Link2SD disappears as if it was uninstalled without any notice, it occurs randomly after rebooting the device.
-Is it safe to clean dalvik cache from Link2SD options? I did it a while ago and I think this is the only solution so far. Dalvik cache covers the data a half space of it O.o
Anyway, is the main problem caused by Link2SD app or the new partitioning layout? what do you think?

Log: http://goo.gl/Xd86Dd
![screenshot_2013-12-26-20-40-40](https://f.cloud.github.com/assets/5206764/1813844/b0d0da2e-6ed6-11e3-86b1-f20973610f54.png)
![screenshot_2013-12-27-04-02-57](https://f.cloud.github.com/assets/5206764/1813845/b692d0c0-6ed6-11e3-9000-b0caef07eb05.png)
![screenshot_2013-12-27-04-03-08](https://f.cloud.github.com/assets/5206764/1813846/b844056a-6ed6-11e3-9ff8-9ea0c3e6857b.png)

EDIT
This issue is present on any versions of Android (Tested on CM10 up to CM11) it only means that there might be something wrong with Link2SD itself, not sure about this. I'll just wait for someone that has more knowledge and skills about this :)
Another logcat came from CM10 http://goo.gl/rUOjZh

**Comment by a9402465** [comment]
I have exactly the same problem with [CM11] {satsuma}. During the boot process, applications, libraries and cache files often get unlinked (Android is "optimizing" applications), whereafter the internal memory is full, making many applications force-close including android.process.media. After that many apps become unusable unless manually reinstalling them again. It would be great to know how to make Android not relink applications to internal memory during boot, as this seems the root-cause of many issues...

**Comment by JovieBrett** [comment]
@a9402465 I forgot to add the issue you mentioned, yeah everytime I reboot the device, "Android is optimizing" is always present during the boot process, it's just really annoying then after that almost all of the apps will force close causing the whole system unusable. This was an issue on the second alpha build then it got fixed when an update of Link2SD arrived and following that day, Mike decided to make some changes for the partition layout to make ART usable by adding dalvik cache to /data, someone correct me if I'm wrong... After that, dalvik cache is messing up with /data partition by filling all of the space left on /data.

EDIT
I forgot that this issue is also presented in CM10.2 latest build. Relinking apps using Link2SD caused my device to soft reboot. I think this issue is really related with Link2SD...

**Comment by vbenes** [comment]
for my urushi, I've deleted some apps from image and now I am super OK with free space and link2SD is not needed anymore. diff is here if interested. No FCs and missing apps can be installed from market. I stripped languages, fonts and some more stuff as well.
http://pastebin.com/Z1SC9W84

**Comment by vbenes** [comment]
I am using ART and battery really rocks! phone is super fast. I cleaned dalvik cache after switching to ART so there is no space taken by dalvik but only ART

**Comment by s-kostyuk** [comment]
[offtop, sorry] @vbenes what is needed to switch to ART? Haida, latest bulid, some apps is linked with App2SD.

**Comment by JovieBrett** [comment]
@vbenes are you using the latest build? because the previous builds without modified partition layouts are having troubles with apps that causes to force close because /system is running out of space but that was fixed on the latest build released by Mike, however the problem right now is that the dalvik cache is filling up the /data rapidly during the boot process causing some and almost all of the apps to be unstable and make force closes after the boot process. Somehow, there is a temporary fix for this by waiting a couple of minutes every after the boot process and wiping the dalvik cache via Link2SD which is inconvinient for me and not required for a daily driver.

**Comment by vbenes** [comment]
yes, I am using 1226, but I have no issue with cache filling, just wanted to state that there is an option to free up some space when using ART. Otherwise ART enabled ROMs are quite unusable as there is really too little space there to install other apps.

**Comment by vbenes** [comment]
@VeryStrangeMan you need to click 10 times on build name in telephone info, that unlocks developer menu, there is ART enablement in runtime module menu item.

**Comment by s-kostyuk** [comment]
@vbenes I had in mind any tips for switching. Wipe/delete/uninstall/unlink/etc. something for better experience. But anyway thank you and probrem is not actual now (already switched about 3 hours ago :) ). And sorry for my English and this offtop.

**Comment by mikeNG** [comment]
please test the latest build

**Comment by JovieBrett** [comment]
Hi @mikeNG I think this issue has been fixed by the latest build01212014 you released. However, everytime I reboot the device 'Android is upgrading' boot process is still there but the difference is it doesn't take so long anymore :+1: 
('Android is upgrading' process is not a problem for me so...)
Dalvik-cache is normal again and I haven't had any force closes from my apps that are linked via Link2SD. Also kernel boot time is now faster!
So, I may now close this issue since everything is now running good, thank you Michael!

**Comment by a9402465** [comment]
I installed the new build01212014, but unfortunately the problem still exists. Android is still "optimizing" during startup, which still breaks the links of linked applications and fills up the /data partition. Only after relinking all linked apps, the memory in /data becomes available again.
