### ISSUE TITLE
cm-11.0-20131225-NIGHTLY-LegacyXperia-haida

### ISSUE THREAD

**Issue by Jithug** [LegacyXperia/local_manifests#357]
Camera Recording stopped.Not Working,please fix..

**Comment by sidharthgtm** [comment]
Bug fixed by Dev.

**Comment by Jithug** [comment]
no still not working..stucks camera and stops its kitkat.bug..

**Comment by sidharthgtm** [comment]
wait for upcoming build

**Comment by Jithug** [comment]
are you develeper

**Comment by ghost** [comment]
No he's not but at least he can read: https://github.com/LegacyXperia/local_manifests/wiki/Changelog
