### ISSUE TITLE
[10.2] Camera preview freezes, then FC

### ISSUE THREAD

**Issue by djey47** [LegacyXperia/local_manifests#41]
After taking a few shots succesfully, reviewing them in 'pellicule ' (film?) layout, then back to capture mode, on screen preview does not itself update any more. 
Trigger button seems inactive, when insisting, camera app FCs.

Latest build : 20130828 + included Kernel
Device : haida

Here is the log : 
--------- beginning of /dev/log/system
08-30 01:08:01.473 E/AndroidRuntime(13073): FATAL EXCEPTION: Camera Handler Thread
08-30 01:08:01.473 E/AndroidRuntime(13073): java.lang.RuntimeException: setParameters failed
08-30 01:08:01.473 E/AndroidRuntime(13073):     at android.hardware.Camera.native_setParameters(Native Method)
08-30 01:08:01.473 E/AndroidRuntime(13073):     at android.hardware.Camera.setParameters(Camera.java:1540)
08-30 01:08:01.473 E/AndroidRuntime(13073):     at com.android.camera.CameraManager$CameraHandler.handleMessage(CameraManager.java:237)
08-30 01:08:01.473 E/AndroidRuntime(13073):     at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 01:08:01.473 E/AndroidRuntime(13073):     at android.os.Looper.loop(Looper.java:137)
08-30 01:08:01.473 E/AndroidRuntime(13073):     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by n1kolaa** [comment]
did you done date wipe and chase wipe?

**Comment by djey47** [comment]
Yes, all wipes, clean install as usual. 
Will try to reproduce once again to give further details.

**Comment by djey47** [comment]
Reproduced. Steps to follow : 
- change settings to 3.7mp
- take photograph

=> Preview is now frozen, + green sometimes
- try to pinch zoom 

=> FC

It only occurs with 3.7mp setting, all other options work actually. I would not be surprised the phone can't handle it. The best thing would be to remove corresponding option.

Here are more logs:
http://pastebin.com/0p2nSz3u

**Comment by djey47** [comment]
Here are more logs before FC:

http://pastebin.com/D2081PmL

**Comment by djey47** [comment]
Latest build, 20130918, 10.2, haida :

Always same freeze issue, only with 3.7Mpix setting. Neo v can't support it so it would be cool it to be removed from list.
But not a real issue anyway, I can live with this ^^.

I haven't noticed any green bar for the moment, looks like it has been solved.

Only ugly thing is a green thumbnail always appearing in right hand corner after shot.
See attached picture.

![media-20130921](https://f.cloud.github.com/assets/2901949/1185581/a5018eae-22b5-11e3-8840-f714a3f4b13f.png)

**Comment by mikeNG** [comment]
Any news with the latest build?

**Comment by djey47** [comment]
Confirmed. Green thumbnail still there in CM10.2 20131013 - Haida.

Concerning preview freeze + FC, it still occurs @3.7mpx. Freeze at least, sometimes green, sometimes normal color.
Though, it does not FC anymore :)

---

Here is log :
http://pastebin.com/6Mh9EK0w

**Comment by mikeNG** [comment]
Green thumbnail bug can't be fixed and it's a minor eye-candy issue. The photos are taken fine and are not green.

@djey47 please use pastebin or some similar site to post logs next time.

About your crash, I can see in the log:

```
/dev/pmem_adsp: failed to map pmem fd: Out of memory
```

Your device is haida with 5MP camera right? I will look into this. It seems camera needs more pmem to work.

**Comment by djey47** [comment]
Ok for pastebin, sorry.
And I agree for green thumb, it's not a serious issue, I can live with this :)

Yes, device is neo V (haida), 5MPx cam.

Thanks Mike.

**Comment by mikeNG** [comment]
Should be fixed in next build

**Comment by djey47** [comment]
Still freezing at 3.7 mpix on latest build.
http://pastebin.com/KZbdRfAK

**Comment by mikeNG** [comment]
Can you check the newest build?

**Comment by djey47** [comment]
Hi,
I will test with 20131112-cm10.2 when I'll get it installed on haida,
but for my current version (20131108-cm10.2), just tested and 3.7Mpix is working now!
Thanks.

**Comment by djey47** [comment]
Sad to tell, but the issue is back again, latest build :(

Here are the logs :
https://gist.github.com/djey47/3726cbc60e74e05538e6
(11-21 15:22:58.375 E/caladbolg(230): 1817617279 cald_camctrl.c                    (8582)  8542 E [SVR] preview buffer not found)

Btw, what are those dequeue/cancel buffer messages polluting logcat ? :o

**Comment by mikeNG** [comment]
weird...
any specific steps needed to reproduce the issue?

**Comment by djey47** [comment]
- start camera app
- go to settings, resolutions
- select 3.7mpix
- try to take a pic

-> the screen is now frozen, and picture not saved.

Closing and opening app allows to go to settings and change to 5mpix, and works as before.

**Comment by mikeNG** [comment]
are you able to build the rom from source?

**Comment by djey47** [comment]
I'm afraid I have to learn how to do it, would be interesting but I have no time at the moment :(

**Comment by djey47** [comment]
Works with latest RC build. I'm closing this now.
Thanks.

**Comment by mikeNG** [comment]
Nice :)
