### ISSUE TITLE
Settings wiped after reboot. CM11. iyokan.

### ISSUE THREAD

**Issue by pteek** [LegacyXperia/local_manifests#577]
I thought I'd make a general thread.
1. The "sort by" setting defaults to Title on reboot. And no matter which one of the three is selected, the current settings is always displayed as Install Time.
2. Privacy guard settings for apps moved to sd by native method are reset to default on reboot.

Please add any more reboot reset or related issues here.

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by pteek** [comment]
Still present on 20140512.
log before reboot:
http://bayfiles.net/file/1ee5U/Hwjcyx/2014-05-18_07.26.zip
log after the reboot: privacy guard is turned off for the app moved to sd(contra)
http://bayfiles.net/file/1ee6n/pmkjEZ/2014-05-18_07.29.zip

**Comment by pteek** [comment]
Update:
The launcher settings are reset even if trebuchet is restated(Force close or crash). No need to reboot.
Still present on 20140604

**Comment by mikeNG** [comment]
This should fix the Trebuchet bug http://review.cyanogenmod.org/#/c/65506/

**Comment by mikeNG** [comment]
This should fix the privacy guard bug http://review.cyanogenmod.org/#/c/65451/

**Comment by pteek** [comment]
Fixed in 20140703!

**Comment by pteek** [comment]
In the new builds(I noticed from 20140906 onwards, still present in 20141006), privacy guard is reset for some applications moved to sd. Happens only with firefox and MX player. I will post logs soon.
